[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-args=/STACK:8388608"]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "link-args=/STACK:8388608"]

[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "link-args=-Wl,--stack,8388608"]

[target.i686-pc-windows-gnu]
rustflags = ["-C", "link-args=-Wl,--stack,8388608"]
