/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 44
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 32
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 11
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__document_title_heading_marker = 1,
  sym__document_title_text_content = 2,
  anon_sym_SEMI = 3,
  sym__document_author_line_name = 4,
  sym__document_author_line_email_address = 5,
  anon_sym_LT = 6,
  anon_sym_GT = 7,
  sym__word_chars_with_dash = 8,
  sym__document_revision_line_date_text = 9,
  sym__document_revision_line_version_text = 10,
  anon_sym_COLON = 11,
  anon_sym_COMMA = 12,
  sym__document_attribute_name_marker = 13,
  sym__document_attribute_value_text = 14,
  sym__newline = 15,
  sym__space = 16,
  sym_source_file = 17,
  sym_document_title = 18,
  sym_document_author_line = 19,
  sym__document_author_line_semi_colon = 20,
  sym__document_author_line_email_start_marker = 21,
  sym__document_author_line_email_end_marker = 22,
  sym_document_revision_line = 23,
  sym__document_revision_line_colon = 24,
  sym__document_revision_line_comma = 25,
  sym_document_attribute = 26,
  aux_sym_document_title_repeat1 = 27,
  aux_sym_document_author_line_repeat1 = 28,
  aux_sym_document_author_line_repeat2 = 29,
  aux_sym_document_revision_line_repeat1 = 30,
  aux_sym_document_revision_line_repeat2 = 31,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__document_title_heading_marker] = "_document_title_heading_marker",
  [sym__document_title_text_content] = "_document_title_text_content",
  [anon_sym_SEMI] = ";",
  [sym__document_author_line_name] = "_document_author_line_name",
  [sym__document_author_line_email_address] = "_document_author_line_email_address",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [sym__word_chars_with_dash] = "_word_chars_with_dash",
  [sym__document_revision_line_date_text] = "_document_revision_line_date_text",
  [sym__document_revision_line_version_text] = "_document_revision_line_version_text",
  [anon_sym_COLON] = ":",
  [anon_sym_COMMA] = ",",
  [sym__document_attribute_name_marker] = "_document_attribute_name_marker",
  [sym__document_attribute_value_text] = "_document_attribute_value_text",
  [sym__newline] = "_newline",
  [sym__space] = "_space",
  [sym_source_file] = "source_file",
  [sym_document_title] = "document_title",
  [sym_document_author_line] = "document_author_line",
  [sym__document_author_line_semi_colon] = "_document_author_line_semi_colon",
  [sym__document_author_line_email_start_marker] = "_document_author_line_email_start_marker",
  [sym__document_author_line_email_end_marker] = "_document_author_line_email_end_marker",
  [sym_document_revision_line] = "document_revision_line",
  [sym__document_revision_line_colon] = "_document_revision_line_colon",
  [sym__document_revision_line_comma] = "_document_revision_line_comma",
  [sym_document_attribute] = "document_attribute",
  [aux_sym_document_title_repeat1] = "document_title_repeat1",
  [aux_sym_document_author_line_repeat1] = "document_author_line_repeat1",
  [aux_sym_document_author_line_repeat2] = "document_author_line_repeat2",
  [aux_sym_document_revision_line_repeat1] = "document_revision_line_repeat1",
  [aux_sym_document_revision_line_repeat2] = "document_revision_line_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__document_title_heading_marker] = sym__document_title_heading_marker,
  [sym__document_title_text_content] = sym__document_title_text_content,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym__document_author_line_name] = sym__document_author_line_name,
  [sym__document_author_line_email_address] = sym__document_author_line_email_address,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [sym__word_chars_with_dash] = sym__word_chars_with_dash,
  [sym__document_revision_line_date_text] = sym__document_revision_line_date_text,
  [sym__document_revision_line_version_text] = sym__document_revision_line_version_text,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym__document_attribute_name_marker] = sym__document_attribute_name_marker,
  [sym__document_attribute_value_text] = sym__document_attribute_value_text,
  [sym__newline] = sym__newline,
  [sym__space] = sym__space,
  [sym_source_file] = sym_source_file,
  [sym_document_title] = sym_document_title,
  [sym_document_author_line] = sym_document_author_line,
  [sym__document_author_line_semi_colon] = sym__document_author_line_semi_colon,
  [sym__document_author_line_email_start_marker] = sym__document_author_line_email_start_marker,
  [sym__document_author_line_email_end_marker] = sym__document_author_line_email_end_marker,
  [sym_document_revision_line] = sym_document_revision_line,
  [sym__document_revision_line_colon] = sym__document_revision_line_colon,
  [sym__document_revision_line_comma] = sym__document_revision_line_comma,
  [sym_document_attribute] = sym_document_attribute,
  [aux_sym_document_title_repeat1] = aux_sym_document_title_repeat1,
  [aux_sym_document_author_line_repeat1] = aux_sym_document_author_line_repeat1,
  [aux_sym_document_author_line_repeat2] = aux_sym_document_author_line_repeat2,
  [aux_sym_document_revision_line_repeat1] = aux_sym_document_revision_line_repeat1,
  [aux_sym_document_revision_line_repeat2] = aux_sym_document_revision_line_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__document_title_heading_marker] = {
    .visible = false,
    .named = true,
  },
  [sym__document_title_text_content] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym__document_author_line_name] = {
    .visible = false,
    .named = true,
  },
  [sym__document_author_line_email_address] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym__word_chars_with_dash] = {
    .visible = false,
    .named = true,
  },
  [sym__document_revision_line_date_text] = {
    .visible = false,
    .named = true,
  },
  [sym__document_revision_line_version_text] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym__document_attribute_name_marker] = {
    .visible = false,
    .named = true,
  },
  [sym__document_attribute_value_text] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__space] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_document_title] = {
    .visible = true,
    .named = true,
  },
  [sym_document_author_line] = {
    .visible = true,
    .named = true,
  },
  [sym__document_author_line_semi_colon] = {
    .visible = false,
    .named = true,
  },
  [sym__document_author_line_email_start_marker] = {
    .visible = false,
    .named = true,
  },
  [sym__document_author_line_email_end_marker] = {
    .visible = false,
    .named = true,
  },
  [sym_document_revision_line] = {
    .visible = true,
    .named = true,
  },
  [sym__document_revision_line_colon] = {
    .visible = false,
    .named = true,
  },
  [sym__document_revision_line_comma] = {
    .visible = false,
    .named = true,
  },
  [sym_document_attribute] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_title_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_document_author_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_document_author_line_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_document_revision_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_document_revision_line_repeat2] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_authors = 1,
  field_date = 2,
  field_email = 3,
  field_marker = 4,
  field_message = 5,
  field_name = 6,
  field_title = 7,
  field_value = 8,
  field_version = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_authors] = "authors",
  [field_date] = "date",
  [field_email] = "email",
  [field_marker] = "marker",
  [field_message] = "message",
  [field_name] = "name",
  [field_title] = "title",
  [field_value] = "value",
  [field_version] = "version",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 2},
  [6] = {.index = 9, .length = 3},
  [7] = {.index = 12, .length = 3},
  [8] = {.index = 15, .length = 6},
  [9] = {.index = 21, .length = 4},
  [10] = {.index = 25, .length = 7},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_version, 0},
  [1] =
    {field_marker, 0},
    {field_title, 1},
  [3] =
    {field_authors, 0},
    {field_authors, 1},
  [5] =
    {field_name, 0},
    {field_value, 1},
  [7] =
    {field_date, 2},
    {field_version, 0},
  [9] =
    {field_authors, 0},
    {field_authors, 1},
    {field_authors, 2},
  [12] =
    {field_message, 2},
    {field_message, 3},
    {field_version, 0},
  [15] =
    {field_authors, 0},
    {field_authors, 1},
    {field_email, 2},
    {field_email, 3},
    {field_email, 4},
    {field_email, 5},
  [21] =
    {field_date, 2},
    {field_message, 4},
    {field_message, 5},
    {field_version, 0},
  [25] =
    {field_authors, 0},
    {field_authors, 1},
    {field_authors, 2},
    {field_email, 3},
    {field_email, 4},
    {field_email, 5},
    {field_email, 6},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(19);
      ADVANCE_MAP(
        ',', 36,
        '-', 31,
        ':', 35,
        ';', 26,
        '<', 29,
        '>', 30,
        'v', 23,
        '#', 20,
        '=', 20,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(22);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(40);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(42);
      if ((0x0b <= lookahead && lookahead <= '\r')) SKIP(1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(3);
      if (lookahead == '@') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(4);
      if (lookahead == ',' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(4);
      if (lookahead == ',' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(5);
      if (lookahead == ',' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 6:
      if (lookahead == '.') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(15);
      if (lookahead == '<') ADVANCE(29);
      if (lookahead == 'v') ADVANCE(13);
      if (lookahead == '#' ||
          lookahead == '=') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(37);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '@') ADVANCE(16);
      if (lookahead == ' ' ||
          lookahead == ',' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 10:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 11:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(39);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 14:
      if (lookahead == '.' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 15:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 16:
      if (lookahead == ' ' ||
          lookahead == ',' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 17:
      if (eof) ADVANCE(19);
      if (lookahead == ';') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(43);
      if (('\n' <= lookahead && lookahead <= '\r')) SKIP(17);
      END_STATE();
    case 18:
      if (eof) ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym__document_title_heading_marker);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym__document_title_text_content);
      if (lookahead == '-') ADVANCE(31);
      if (lookahead == '.') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym__document_title_text_content);
      if (lookahead == '-') ADVANCE(31);
      if (lookahead == '.') ADVANCE(27);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(24);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym__document_title_text_content);
      if (lookahead == '-') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym__document_title_text_content);
      if (lookahead == '-') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym__document_title_text_content);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym__document_author_line_name);
      if (lookahead == '.' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym__document_author_line_email_address);
      if (lookahead == ' ' ||
          lookahead == ',' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym__word_chars_with_dash);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym__document_revision_line_date_text);
      if (lookahead == ' ') ADVANCE(32);
      if (lookahead == ',' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym__document_revision_line_date_text);
      if (lookahead == ' ' ||
          lookahead == ',' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym__document_revision_line_version_text);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym__document_attribute_name_marker);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym__document_attribute_value_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym__document_attribute_value_text);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(40);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(42);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym__space);
      if (lookahead == '\n') ADVANCE(40);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym__space);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(43);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 7},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 17},
  [4] = {.lex_state = 17},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 17},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 17},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 18},
  [11] = {.lex_state = 7},
  [12] = {.lex_state = 17},
  [13] = {.lex_state = 18},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 7},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 7},
  [22] = {.lex_state = 17},
  [23] = {.lex_state = 17},
  [24] = {.lex_state = 18},
  [25] = {.lex_state = 10},
  [26] = {.lex_state = 10},
  [27] = {.lex_state = 17},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 10},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 11},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 7},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__document_title_heading_marker] = ACTIONS(1),
    [sym__document_title_text_content] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym__document_author_line_name] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym__word_chars_with_dash] = ACTIONS(1),
    [sym__document_revision_line_version_text] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(37),
    [sym_document_title] = STATE(38),
    [sym_document_author_line] = STATE(38),
    [sym_document_revision_line] = STATE(38),
    [sym_document_attribute] = STATE(38),
    [aux_sym_document_author_line_repeat2] = STATE(21),
    [sym__document_title_heading_marker] = ACTIONS(3),
    [sym__document_author_line_name] = ACTIONS(5),
    [sym__document_revision_line_version_text] = ACTIONS(7),
    [sym__document_attribute_name_marker] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      anon_sym_COLON,
    ACTIONS(15), 1,
      anon_sym_COMMA,
    STATE(25), 1,
      sym__document_revision_line_colon,
    STATE(33), 1,
      sym__document_revision_line_comma,
  [16] = 5,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      anon_sym_SEMI,
    ACTIONS(21), 1,
      sym__space,
    STATE(6), 1,
      aux_sym_document_author_line_repeat1,
    STATE(39), 1,
      sym__document_author_line_semi_colon,
  [32] = 5,
    ACTIONS(19), 1,
      anon_sym_SEMI,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      sym__space,
    STATE(6), 1,
      aux_sym_document_author_line_repeat1,
    STATE(39), 1,
      sym__document_author_line_semi_colon,
  [48] = 3,
    ACTIONS(29), 1,
      sym__space,
    STATE(7), 1,
      aux_sym_document_revision_line_repeat1,
    ACTIONS(27), 2,
      sym__word_chars_with_dash,
      sym__newline,
  [59] = 4,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    ACTIONS(33), 1,
      anon_sym_SEMI,
    ACTIONS(35), 1,
      sym__space,
    STATE(6), 1,
      aux_sym_document_author_line_repeat1,
  [72] = 3,
    ACTIONS(29), 1,
      sym__space,
    STATE(9), 1,
      aux_sym_document_revision_line_repeat1,
    ACTIONS(38), 2,
      sym__word_chars_with_dash,
      sym__newline,
  [83] = 4,
    ACTIONS(19), 1,
      anon_sym_SEMI,
    ACTIONS(40), 1,
      sym__space,
    STATE(6), 1,
      aux_sym_document_author_line_repeat1,
    STATE(39), 1,
      sym__document_author_line_semi_colon,
  [96] = 3,
    ACTIONS(44), 1,
      sym__space,
    STATE(9), 1,
      aux_sym_document_revision_line_repeat1,
    ACTIONS(42), 2,
      sym__word_chars_with_dash,
      sym__newline,
  [107] = 3,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(49), 1,
      sym__document_title_text_content,
    STATE(13), 1,
      aux_sym_document_title_repeat1,
  [117] = 3,
    ACTIONS(51), 1,
      sym__document_author_line_name,
    ACTIONS(53), 1,
      anon_sym_LT,
    STATE(31), 1,
      sym__document_author_line_email_start_marker,
  [127] = 2,
    ACTIONS(33), 1,
      anon_sym_SEMI,
    ACTIONS(31), 2,
      ts_builtin_sym_end,
      sym__space,
  [135] = 3,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
    ACTIONS(57), 1,
      sym__document_title_text_content,
    STATE(13), 1,
      aux_sym_document_title_repeat1,
  [145] = 3,
    ACTIONS(60), 1,
      sym__word_chars_with_dash,
    ACTIONS(62), 1,
      sym__newline,
    STATE(16), 1,
      aux_sym_document_revision_line_repeat2,
  [155] = 3,
    ACTIONS(64), 1,
      ts_builtin_sym_end,
    ACTIONS(66), 1,
      anon_sym_COLON,
    STATE(26), 1,
      sym__document_revision_line_colon,
  [165] = 3,
    ACTIONS(68), 1,
      sym__word_chars_with_dash,
    ACTIONS(71), 1,
      sym__newline,
    STATE(16), 1,
      aux_sym_document_revision_line_repeat2,
  [175] = 1,
    ACTIONS(42), 3,
      sym__word_chars_with_dash,
      sym__newline,
      sym__space,
  [181] = 3,
    ACTIONS(51), 1,
      sym__document_author_line_name,
    ACTIONS(73), 1,
      anon_sym_LT,
    STATE(40), 1,
      sym__document_author_line_email_start_marker,
  [191] = 3,
    ACTIONS(60), 1,
      sym__word_chars_with_dash,
    ACTIONS(75), 1,
      sym__newline,
    STATE(16), 1,
      aux_sym_document_revision_line_repeat2,
  [201] = 2,
    ACTIONS(77), 1,
      anon_sym_GT,
    STATE(41), 1,
      sym__document_author_line_email_end_marker,
  [208] = 2,
    ACTIONS(79), 1,
      sym__document_author_line_name,
    STATE(28), 1,
      aux_sym_document_author_line_repeat2,
  [215] = 2,
    ACTIONS(40), 1,
      sym__space,
    STATE(3), 1,
      aux_sym_document_author_line_repeat1,
  [222] = 2,
    ACTIONS(40), 1,
      sym__space,
    STATE(8), 1,
      aux_sym_document_author_line_repeat1,
  [229] = 2,
    ACTIONS(81), 1,
      sym__document_title_text_content,
    STATE(10), 1,
      aux_sym_document_title_repeat1,
  [236] = 2,
    ACTIONS(83), 1,
      sym__word_chars_with_dash,
    STATE(14), 1,
      aux_sym_document_revision_line_repeat2,
  [243] = 2,
    ACTIONS(83), 1,
      sym__word_chars_with_dash,
    STATE(19), 1,
      aux_sym_document_revision_line_repeat2,
  [250] = 2,
    ACTIONS(40), 1,
      sym__space,
    STATE(4), 1,
      aux_sym_document_author_line_repeat1,
  [257] = 2,
    ACTIONS(85), 1,
      sym__document_author_line_name,
    STATE(28), 1,
      aux_sym_document_author_line_repeat2,
  [264] = 2,
    ACTIONS(88), 1,
      anon_sym_GT,
    STATE(43), 1,
      sym__document_author_line_email_end_marker,
  [271] = 1,
    ACTIONS(51), 1,
      sym__document_author_line_name,
  [275] = 1,
    ACTIONS(90), 1,
      sym__document_author_line_email_address,
  [279] = 1,
    ACTIONS(92), 1,
      sym__word_chars_with_dash,
  [283] = 1,
    ACTIONS(94), 1,
      sym__document_revision_line_date_text,
  [287] = 1,
    ACTIONS(96), 1,
      ts_builtin_sym_end,
  [291] = 1,
    ACTIONS(98), 1,
      ts_builtin_sym_end,
  [295] = 1,
    ACTIONS(100), 1,
      sym__document_attribute_value_text,
  [299] = 1,
    ACTIONS(102), 1,
      ts_builtin_sym_end,
  [303] = 1,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
  [307] = 1,
    ACTIONS(106), 1,
      sym__document_author_line_name,
  [311] = 1,
    ACTIONS(108), 1,
      sym__document_author_line_email_address,
  [315] = 1,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
  [319] = 1,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
  [323] = 1,
    ACTIONS(114), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 16,
  [SMALL_STATE(4)] = 32,
  [SMALL_STATE(5)] = 48,
  [SMALL_STATE(6)] = 59,
  [SMALL_STATE(7)] = 72,
  [SMALL_STATE(8)] = 83,
  [SMALL_STATE(9)] = 96,
  [SMALL_STATE(10)] = 107,
  [SMALL_STATE(11)] = 117,
  [SMALL_STATE(12)] = 127,
  [SMALL_STATE(13)] = 135,
  [SMALL_STATE(14)] = 145,
  [SMALL_STATE(15)] = 155,
  [SMALL_STATE(16)] = 165,
  [SMALL_STATE(17)] = 175,
  [SMALL_STATE(18)] = 181,
  [SMALL_STATE(19)] = 191,
  [SMALL_STATE(20)] = 201,
  [SMALL_STATE(21)] = 208,
  [SMALL_STATE(22)] = 215,
  [SMALL_STATE(23)] = 222,
  [SMALL_STATE(24)] = 229,
  [SMALL_STATE(25)] = 236,
  [SMALL_STATE(26)] = 243,
  [SMALL_STATE(27)] = 250,
  [SMALL_STATE(28)] = 257,
  [SMALL_STATE(29)] = 264,
  [SMALL_STATE(30)] = 271,
  [SMALL_STATE(31)] = 275,
  [SMALL_STATE(32)] = 279,
  [SMALL_STATE(33)] = 283,
  [SMALL_STATE(34)] = 287,
  [SMALL_STATE(35)] = 291,
  [SMALL_STATE(36)] = 295,
  [SMALL_STATE(37)] = 299,
  [SMALL_STATE(38)] = 303,
  [SMALL_STATE(39)] = 307,
  [SMALL_STATE(40)] = 311,
  [SMALL_STATE(41)] = 315,
  [SMALL_STATE(42)] = 319,
  [SMALL_STATE(43)] = 323,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document_revision_line, 1, 0, 1),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document_author_line, 2, 0, 3),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document_author_line, 3, 0, 6),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_document_revision_line_repeat2, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_author_line_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_document_author_line_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_author_line_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_document_revision_line_repeat2, 2, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_document_revision_line_repeat1, 2, 0, 0),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_revision_line_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document_title, 2, 0, 2),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_title_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_title_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document_revision_line, 3, 0, 5),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_revision_line_repeat2, 2, 0, 0), SHIFT_REPEAT(5),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_revision_line_repeat2, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_author_line_repeat2, 2, 0, 0), SHIFT_REPEAT(23),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document_revision_line, 4, 0, 7),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document_attribute, 2, 0, 4),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [102] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_author_line_repeat2, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document_author_line, 6, 0, 8),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document_revision_line, 6, 0, 9),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document_author_line, 7, 0, 10),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_asciidoc(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "asciidoc",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
